//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT.CorsoCSharp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPI_CARBURANTI
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public bool Electric { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<double> Liters { get; set; }
        public Nullable<int> Station_ID { get; set; }
    
        public virtual Station Station { get; set; }
    }
}
